### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [ruby/fiddle#104]
JRuby ships an implementation of fiddle based on FFI, and cannot support the C extension contained in this gem. It may be possible for us to do what @chrisseaton did and add a native fiddle implementation, but for now we would like to incorporate our own fiddle implementation into this gem, so that we can use it and users can reference it.

**Comment by kou** [comment]
+1

What should we do for it as the next step?

**Comment by rubyFeedback** [comment]
This would be interesting e. g. if we could then use fiddle + jruby for the libui bindings maintained by kojix2. I have not tried this yet (I usually use MRI as-is) but that would be really interesting, even more so with graalvm (if we can manage to compile everything into one app on windows one day; easy-mode distribution for elderly people who may need that. That is one use case I have for java swing, but of course I'd love to use jruby or any ruby-centric application for that).

**Comment by headius** [comment]
I will review the additional changes and we will probably pull this version into JRuby, just not as a gem until JRuby 10.
