### ISSUE TITLE
Can't open linker script files

### ISSUE THREAD

**Issue by nevans** [ruby/fiddle#107]
On my Ubuntu 21.04 installation, several shared libraries .so files are installed as [linker scripts] instead of using a symlink.  In my research, I see that this is done (or has been done) in [Debian], [CentOS], [Fedora], RHEL, Gentoo, and maybe Arch (I didn't personally verify the last two).  This shouldn't a big deal if you link at compile time with GNU `ld`, but it breaks `dlopen`.

[linker scripts]: https://sourceware.org/binutils/docs-2.38/ld/Scripts.html#Scripts
[Debian]: https://sources.debian.org/src/ncurses/6.2%2B20201114-2/debian/rules/#L447
[CentOS]: https://git.centos.org/rpms/ncurses/blob/c8/f/SPECS/ncurses.spec#_224
[Fedora]: https://src.fedoraproject.org/rpms/ncurses/blob/f32/f/ncurses.spec#_213

I found workarounds in the [ffi gem] and in [ghc], and perhaps one of those could be copied into fiddle.

[ffi gem]: https://github.com/ffi/ffi/blob/447845cb3030194c79700c86fb388a12e6f81386/lib/ffi/library.rb#L115-L141
[ghc]:  https://github.com/ghc/ghc/blob/88d610317a707eb33fe8f1a1a8ab6456279861f2/rts/Linker.c#L651-L695

A workaround for users of `fiddle` might be to attempt to loading a specific version of the library:

```console
irb(main):005:0> File.read "/lib/x86_64-linux-gnu/libncurses.so"
=> "INPUT(libncurses.so.6 -ltinfo)\n"
irb(main):006:0> Fiddle::Handle.new("libncurses.so")
(irb):6:in `initialize': /lib/x86_64-linux-gnu/libncurses.so: file too short (Fiddle::DLError)
	from (irb):6:in `new'                              
	from (irb):6:in `<main>'                           
	from /home/nick/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /home/nick/.rbenv/versions/3.1.1/bin/irb:25:in `load'
	from /home/nick/.rbenv/versions/3.1.1/bin/irb:25:in `<main>'
irb(main):007:0> Fiddle::Handle.new("libncurses.so.6")
=> #<Fiddle::Handle:0x00007fcfbb858670>
```

**Comment by chrisseaton** [comment]
Hi what are you struggling to open?

**Comment by nevans** [comment]
I'm so sorry, I accidentally hit enter when I'd only just started creating the ticket!  I was hoping I'd be able to fill in the details before anyone noticed.  Anyway, I've updated the subject and I'll send a few other details over in a minute.

**Comment by kou** [comment]
Thanks for your report.
I didn't know about linker script.

I've added support for linker script only on Linux for now.

**Comment by nevans** [comment]
Excellent, thanks!
