### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by Eneroth3** [ruby/fiddle#15]
https://github.com/ruby/fiddle/blob/0fc697bbc5c55c5f45ea4f67a6279fba38d2d514/lib/fiddle/import.rb#L88

When dlload in import.rb fails to load it raises an DLError with the message "can't load #{lib}". This is not a very helpful message as it doesn't say anything about why it couldn't load the library.

I've commented out some code for rescuing and re-raising so I could see the original error message, which to me was much more helpful.

Current:
```ruby
          begin
            Fiddle.dlopen(lib)
          rescue DLError
            raise(DLError, "can't load #{lib}")
          end
```

Modified:
```ruby
          #begin
            Fiddle.dlopen(lib)
          #rescue DLError
          #  raise(DLError, "can't load #{lib}")
          #end
```

Perhaps the original message can be included in the new one, or rescuing and re-raising could be removed in favor of the original exception.

Some background information: I'm very new to both Fiddle and C/C++ programming, but have been using Ruby for years. I've (tried to) compile my first ever DLL and use it in a Ruby project using Fiddle. When getting an error saying "Can't load", it is very hard to tell if I did something wrong with my DLL, if I've provided the wrong path or if I am using Fiddle incorrectly in any way.

**Comment by ankane** [comment]
Hey @Eneroth3, not a maintainer, but one way to get around this is:

```rb
dlload Fiddle.dlopen(lib)
```

**Comment by kou** [comment]
Thanks.
It makes sense.
