### ISSUE TITLE
Release and merge into MRI

### ISSUE THREAD

**Issue by chrisseaton** [ruby/fiddle#45]
We've had several fairly significant functionality PRs recently - at least #33, #36, #38, #41, #44.

Might now be the time to make a release and merge into MRI as they start preparing for 3.0?

**Comment by kou** [comment]
I want to release a new version in this month.

**Comment by kou** [comment]
1.0.1 has been released.
I hope that we can merge it into MRI in a few weeks.

**Comment by kou** [comment]
Done.
