### ISSUE TITLE
Build error with `--enable-bundled-libffi` on Apple DTK(arm64)

### ISSUE THREAD

**Issue by hsbt** [ruby/fiddle#46]
I got the following error with the master branch of ruby/ruby repo and `--enable-bundled-liffi` option on Apple DTK(arm64, Big Sur beta6)

https://gist.github.com/hsbt/c4a6cf7dfaf3839998378e9d55faa330

I have no idea to resolve it yet. I will add the additional comment when I find the solution.

**Comment by kou** [comment]
It seems that we need to wait a fix in upstream: https://github.com/libffi/libffi/issues/571
But it seems that there is a workaround for it: https://github.com/Homebrew/homebrew-core/pull/58092

We may need to upgrade our bundled libffi to 3.3 to use the workaround.

**Comment by kou** [comment]
https://github.com/libffi/libffi/pull/565 may be related too.

**Comment by hsbt** [comment]
same as https://github.com/ruby/fiddle/pull/98#issuecomment-1268187869
