### ISSUE TITLE
about Fiddle.free

### ISSUE THREAD

**Issue by ying911008** [ruby/fiddle#71]
I'm not very familiar with C language, But I need to call it, This is my C code:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


char* hello(char* name) {
    char* say = (char*)"Hello ";
    char* welcome = (char*)malloc(strlen(say) + strlen(name));
    sprintf(welcome, "%s%s", say, name);
    return welcome;
}

char* hello2(char* name) {
    char* say = (char*)"Hello ";
    char* welcome = (char*)malloc(strlen(say) + strlen(name));
    sprintf(welcome, "%s%s", say, name);
    return say;
}

```
This is my Ruby code:

```
require 'fiddle'
require 'fiddle/import'

module Lib
  extend Fiddle::Importer
  dlload './77.dll'

  extern 'char* hello(char*)'
end

s = "fa"
a = Lib.hello(s)


Fiddle.free(a.to_i)


f = "asd"
c = Lib.hello2(s)

Fiddle.free(c.to_i)
```
Fiddle.free(a.to_i) is working fine, But call Fiddle.free(c.to_i)，ruby will crash. My question is whether we have to use Fiddle.free to release it? and why Fiddle.free(c.to_i) will crash

**Comment by kou** [comment]
You should not use `Fiddle.free` for both cases.

`Fiddle.free` for memory that is allocated by `ruby_xmallc()` Ruby C API or `Fiddle.malloc`. `Fiddle.free` isn't for memory that is allocated by `malloc()`.

You should use `free()` for memory allocated by `malloc()`.

`hello2()` is invalid in C level. It should not return address of local variable. It's invalid out of the function call.

**Comment by ying911008** [comment]
> You should not use `Fiddle.free` for both cases.
> 
> `Fiddle.free` for memory that is allocated by `ruby_xmallc()` Ruby C API or `Fiddle.malloc`. `Fiddle.free` isn't for memory that is allocated by `malloc()`.
> 
> You should use `free()` for memory allocated by `malloc()`.
> 
> `hello2()` is invalid in C level. It should not return address of local variable. It's invalid out of the function call.

thx
