### ISSUE TITLE
Question: How to allocate an array of structs?

### ISSUE THREAD

**Issue by kojix2** [ruby/fiddle#95]
Hi!

How to allocate an array of structs?
I tried the following code, but it does not work as expected. It may be because the same area is released twice.

```ruby
require 'fiddle/import'

A = Fiddle::Importer.struct [
  'int x',
  'int y'
]

as = Fiddle::Pointer.malloc(A.size * 3)

structs = Array.new(3){ |i|
  size = A.size
  A.new(as.to_i + i * size, size)
}
```

Thank you.

**Comment by kou** [comment]
`A.new`'s second argument is free function not size: `A.new(as.to_i + i * size)`

BTW, you must free `as`.

**Comment by kojix2** [comment]
It's true. I was wrong.

```ruby
require 'fiddle/import'

A = Fiddle::Importer.struct [
  'int x',
  'int y'
]

as = Fiddle::Pointer.malloc(A.size * 3)

structs = Array.new(3){ |i|
  size = A.size
  A.new(as.to_i + i * size)
}
```

When a Fiddle::Pointer is collected in garbage collection, is the memory of the pointer not automatically released?
That is, if no function is specified to release it, it will remain until (or even after?) Ruby exits?

**Comment by kou** [comment]
You can use the second argument for `Fiddle::Pointer.malloc` for free function: `Fiddle::Pointer.malloc(A.size * 3, Fiddle::RUBY_FREE)`.

You can also use block:

```ruby
Fiddle::Pointer.malloc(A.size * 3, Fiddle::RUBY_FREE) do |as|
  # ...
end
```

**Comment by kojix2** [comment]
Wow. This is very useful.
Good to hear.
