### ISSUE TITLE
NetWkstaGetInfo() always fails with INVALID PARAMETER

### ISSUE THREAD

**Issue by fujimotos** [ruby/fiddle#99]
### Environment

 * Windows Server 2019
 * Ruby 2.7.5p203 (2021-11-24 revision f69aeb8314)

### How to reproduce

Run the following script on Windows:

```ruby
require "fiddle/import"
require "fiddle/types"
require "fiddle/import"

module M
  extend Fiddle::Importer
  dlload "netapi32.dll"
  include Fiddle::Win32Types
  extern "int NetWkstaGetInfo(void*, int, void*);"
  # NOTE! If we remove "#" from the following line, it works somehow.
  #extern "int NetWkstaUserGetInfo(void*, int, void*)"
end

buf = "\0" * Fiddle::SIZEOF_VOIDP
pbuf = Fiddle::Pointer[buf]
p M.NetWkstaGetInfo(nil, 102, pbuf)
```

### Bug/Observe

* `NetwkstaGetInfo()` always fails with error code 87 (= "invalid parameter").
  * If we enable  `extern int NetWkstaUserGetInfo(...)` (see line 10-11), it starts working somehow.
* I suspect that there is a subtle bug in FIddle that messes up the function call.

### Expected behavior

 * `NetWkstaGetInfo()` exits with sucecss (= 0) and returns machine info correctly.

**Comment by fujimotos** [comment]
Here are the links for MSDN documentations:

* https://docs.microsoft.com/en-us/windows/win32/api/lmwksta/nf-lmwksta-netwkstagetinfo
* https://docs.microsoft.com/en-us/windows/win32/api/lmwksta/nf-lmwksta-netwkstausergetinfo

**Comment by kou** [comment]
Could you confirm this with Ruby 3.0?

**Comment by kou** [comment]
Could you use `DWORD` or `unsigned long` not `int` for `DWORD` argument?

```ruby
  extern "int NetWkstaGetInfo(void*, DWORD, void*);"
```

**Comment by fujimotos** [comment]
> Could you confirm this with Ruby 3.0?

Yes. I confirmd it fails with error code 87 on Ruby 3.0.3, too.

```cmd
% ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
% ruby issue99.rb
87
```

> Could you use DWORD or unsigned long not int for DWORD argument?

The result is the same. It fails with 87.

**Comment by kou** [comment]
I think that this is not a Fiddle bug.

This is also caused with ffi gem:

```ruby
require 'ffi'

module M
  extend FFI::Library
  ffi_lib 'netapi32.dll'
  attach_function :NetWkstaGetInfo, [ :string, :ulong, :pointer ], :ulong
  #attach_function :NetWkstaUserGetInfo, [ :string, :ulong, :pointer ], :ulong
end

FFI::MemoryPointer.new(:pointer, 1) do |pbuf|
  p M.NetWkstaGetInfo(nil, 102, pbuf)
end
```

It seems that `netapi32.dll` isn't fully initialized until multiple symbols are `GetProcAddress()`-ed. But I don't know the details because I can't see `netapi32.dll`'s implementation. It's not free software.
